# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documenttypes',
            new_name='Documenttype',
        ),
    ]
